language: python
python:
  - "3.8"

install:
  - pip install -U pip pep517 twine
  - pip install -r requirements.txt

script:
  - pytest
  - rm -rf build dist

deploy:
  provider: pypi
  user: __token__
  password:
    secure: $token_secret
  on:
    branch: production
